addons:
 apt:
  packages:
  - valgrind
  - cppcheck
language: c
install:
- make sktest
script:
- valgrind --error-exitcode=1 --track-origins=yes --leak-check=full ./sktest
- cppcheck --error-exitcode=1 -I include/ src
