addons:
 apt:
  packages:
  - valgrind
  - python-numpy
before_install:
  - pip install --user cpp-coveralls cython
language: c
install:
  - make SANFLAGS= tests
  - make -B BUILD=cov tests
script:
  - valgrind --error-exitcode=1 --track-origins=yes --leak-check=full ./tests
  - ./testscov
#  - cd python && make test && cd ..
after_success:
  - coveralls --gcov-options '-o ./ src/*.c'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6be8df01a63d92f7ba79
    on_success: change
    on_failure: always
    on_start: never
