addons:
 apt:
  packages:
  - valgrind
  - cmake
  - cppcheck
language: c
install:
- mkdir -p build
- cd build && cmake .. && make
script:
- cd test
- valgrind --error-exitcode=1 --track-origins=yes --leak-check=full ctest
- cd ../..
- cppcheck --error-exitcode=1 -I include/ src
