addons:
 apt:
  packages:
  - valgrind
  - python-numpy
before_install:
  - pip install --user cpp-coveralls cython
language: c
script:
- make memtest && make clean && make -B EXTRA_CFLAGS="-pg -fprofile-arcs -ftest-coverage" test
- cd python && make test && cd ..
after_success:
- coveralls --gcov-options '-o ./ src/*.c'
