addons:
 apt:
  packages:
  - valgrind
  - cmake
  - cppcheck
language: c
install:
- mkdir -p build
- cd build && cmake .. && make
script:
- valgrind --error-exitcode=1 --track-origins=yes --leak-check=full test/sk_test
- cd ..
- cppcheck --error-exitcode=1 -I include/ src
